SET NAMES UTF8;
DROP DATABASE IF EXISTS tedu;
CREATE DATABASE tedu CHARSET=UTF8;
USE tedu;

CREATE TABLE dept(
  did INT PRIMARY KEY,
  dname VARCHAR(32) NOT NULL,
  location VARCHAR(32) NOT NULL DEFAULT '北京',
  empCount INT NOT NULL DEFAULT 0
);
INSERT INTO dept VALUES(10,'研发部',DEFAULT, DEFAULT);
INSERT INTO dept VALUES(20,'研发部','上海', 3);

CREATE TABLE emp(
  eid INT PRIMARY KEY AUTO_INCREMENT,
  ename VARCHAR(6) NOT NULL,
  idCardNum VARCHAR(18) NOT NULL UNIQUE,
  salary DECIMAL(8,2) DEFAULT NULL,
  deptId INT,
  FOREIGN KEY(deptId) REFERENCES dept(did)
);
INSERT INTO emp VALUES(NULL,'Scott','110',NULL, 20);
INSERT INTO emp VALUES(NULL,'Mary','111',3000, 20);
INSERT INTO emp VALUES(200,'Mary','112',3000, 20);
INSERT INTO emp VALUES(NULL,'Tiger','113',3000, NULL);

INSERT INTO emp VALUES(NULL, 'King', '999', 8000, 20);











